services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-1
    restart: unless-stopped
    ports:
      - "${N8N_PORT}:5678"
    volumes:
      - ./n8n/n8n_data:/home/node/.n8n
    env_file:
      - n8n/n8n.env
    

  # mailhog:
    # image: mailhog:mailhog
    # container_name: mailhog
    # platform: linux/amd64
    # ports:
    # - "${mail_smtp}:1025"
    # - "${mail_ui}:8025"
